### ISSUE TITLE
无法安装应用firmware

### ISSUE THREAD

**Issue by xiayangchun** [wuxx/nanoDAP#1]
你好，想请教一下，我使用STM32F103RBT6下载了boot loader文件后，重新给设备上电，并没有把RST与GND短接，然后识别出来一个U盘（MAINTENANCE），然后我把调试器的应用升级代码放在里面，是个bin文件，名字我随意取的，设备没有反应，我把调试器重新插拔，他还是跳出来U盘（MAINTENANCE），keil里也没有DAPLINK设备，想问下，如何把升级文件安装到下载调试器中，

**Comment by wuxx** [comment]
你应该把固件拖动到里面，而不是bootloader文件，名字可以随意取

**Comment by xiayangchun** [comment]
我拖得是固件，不是bootloader文件，我是使用stlink先把bootloader文件下载到DAPlink里面，这个时候daplink本身是没有应用固件，重新上电出来U盘。没有短接rst和gnd，我把daplink的应用文件拖进去，不是目标固件，重新上电，设备管理器也不出现hid设备，也没有虚拟串口，只有U盘设备，方便留个微信好或者QQ吗，我加你，我的微信和QQ都是308735647

**Comment by wuxx** [comment]
已解决，需要把nRST拉高才能正常使用DAPLink，否则进入的是bootloader
