### ISSUE TITLE
关于SWD访问FLASH

### ISSUE THREAD

**Issue by xidianzhuxi** [wuxx/nanoDAP#11]
我仔细阅读了ADI v5。想请教一下关于擦除和写入Flash这部分的内容，是如何通过SWD做到的呢？换言之，SWD通过操作哪些寄存器可以做到对FLASH的访问呢？

**Comment by wuxx** [comment]
1. 通过SWD接口可以访问任意内存以及CPU寄存器
2. 配置NVIC寄存器，先暂停CPU，将烧录算法和flash数据先写入到SRAM中
3. 修改CPU PC寄存器指向烧录算法区域，再配置NVIC中相关寄存器令CPU恢复执行
4. CPU执行烧录算法，将SRAM中的flash数据写入到Flash中
5. 由于Flash空间一般来说远大于SRAM，所以以上步骤4是不断执行的
以上省略了一些细节操作，详细过程可以参考DAPLink中相关源码 swd_host.c flash_blob.c等
希望对你有所帮助
