### ISSUE TITLE
我想新增一个flash算法该如何修改

### ISSUE THREAD

**Issue by xidianzhuxi** [wuxx/nanoDAP#12]
请教一下，我已经有了一个新的芯片的flash下载算法。想知道本项目更改flash下载算法的代码在哪一块呢？

**Comment by wuxx** [comment]
flash_blob.c

**Comment by xidianzhuxi** [comment]
我搜索到了很多个flash_blob.c，当前生效的是哪一个？

**Comment by wuxx** [comment]
stm32f103xb目录下的

**Comment by xidianzhuxi** [comment]
应该有一处定义了选用那个目录下的吧，是哪一个文件定义了选用哪个目录下的

**Comment by xidianzhuxi** [comment]
我把V1.0的目录单独拿出来，依然能够编译运行，说明该项目中没有包含到software/DAPLink/source里面的flash_blob.c呀。

**Comment by wuxx** [comment]
只有DAPLink才支持拖拽烧录
