### ISSUE TITLE
如何启用Trace功能

### ISSUE THREAD

**Issue by season-studio** [wuxx/nanoDAP#15]
在MDK中的配置中，使能CMSIS DAP下的Trace功能，在基本的SWD连接之外，再将TDO口与目标板的SWO口连接，启动调试。IDE下方状态栏显示“Trace: No Synchronization”。目标板上用代码调用ITM_SendChar也没有任何输出。
用JLink则Trace和ITM输出都正常。

**Comment by wuxx** [comment]
nanoDAP 不支持Trace，TDO只是一个普通的GPIO，没有SWO功能
