### ISSUE TITLE
移植到其他mcu

### ISSUE THREAD

**Issue by ghost** [wuxx/nanoDAP#16]
我能不能把你编译好的固件直接刷写进兼容stm32的mcu上？比如gd32 hk32 apm32等，同为f103cbt6
还是需要自行编译？
（最近stm32涨价太多了，实在买不起

**Comment by thinhx2** [comment]
Yes

**Comment by wuxx** [comment]
只测试过apm32可以，gd32不行

**Comment by thinhx2** [comment]
> 只测试过apm32可以，gd32不行
I agree, for gd32 96mhz instead 72mhz, we must modify source. I know your product cant public firmware, then it just compatible with stm32 alternative 72mhz such as apm32,hk32,mm32

**Comment by nulllaborg** [comment]
gd32 usb枚举时间很慢
