### ISSUE TITLE
程序烧录的时候提示：SWD/JTAG Communication Failure

### ISSUE THREAD

**Issue by 1136132863** [wuxx/nanoDAP#20]
程序烧录的时候提示：SWD/JTAG Communication Failure
且无法正常烧录，开发板供电正常

**Comment by wuxx** [comment]
DAP提示SWD/JTAG Communication Failure或者 RDDI DAP Error 问题排查方法
此种现象是DAP没有检测到目标芯片，什么都不接，出来的就是这个问题现象，最大可能性是接线不对或者接触不良，可根据以下方法排查：
0. 打开Keil Debug -> Settings 标签页检查，注意SWJ勾选框必须勾选
1. 检查一下接线是否接错，或者接触不良，重新插拔，或者换组杜邦线试试看（注意：杜邦线长度最好不要超过30cm）
2. 排查目标板供电是否充足，若目标板功耗较高，尝试目标板单独供电，DAP不对其供电
3. 尝试换一块板子试试看，检查是否下载器问题
4. 尝试换一个下载器测试板子，检查是否是板子的问题
5. 按住目标板的复位按键，再打开这个页面，看其是否有反应，若按住复位按键可以检测到目标芯片，则可根据如下方法解决github.com/wuxx/nanoDAP/wiki/nanoDAP%E4%BD%BF%E7%94%A8%E7%96%91%E9%9A%BE%E6%9D%82%E7%97%87%E8%A7%A3%E6%9E%90
