### ISSUE TITLE
期待离线下载功能！

### ISSUE THREAD

**Issue by Antecer** [wuxx/nanoDAP#22]
既然都实现了拖拽下载hex/bin的功能，那么稍微改改加个按钮做个离线下载功能应该也可以的！

**Comment by wuxx** [comment]
是的，可以，不过离线下载原理并不复杂，可以直接自己重新组织写一个。

**Comment by wuxx** [comment]
可以参考这位老哥的开源项目
https://github.com/XIVN1987/DAPProg
