### ISSUE TITLE
支不支持用nanoDAP JTAG调试VisionFive开发板？

### ISSUE THREAD

**Issue by Artistrs** [wuxx/nanoDAP#23]
您好老师：@wuxx， 我从资料上理解到可以用nanoDAP JTAG调试RISC-V SOC，我的开发板是VisionFive开发板(https://github.com/starfive-tech/VisionFive)，但我之前没用过JTAG，所以需要弄明白搞确切！！！
https://forum.rvspace.org/t/connecting-to-visionfive-s-jtag-port-a-short-guide/514
上面是请教过的内容，还有这一篇关于VisionFive开发板的JTAG详情的文章(https://dram.page/p/visionfive-jtag-1/)！！！

想请老师给我些用nanoDAP JTAG调试RISC-V SOC的指导！！！如果适用VisionFive开发板购买哪款nanoDAP JTAG更合适？？？

**Comment by wuxx** [comment]
你好，应该是用openocd调试对吗，可以的

**Comment by wuxx** [comment]
一般情况推荐使用DAPLink，是最新的开源DAPLink代码，使用上可能更方便

**Comment by Artistrs** [comment]
> 

是的，ubuntu下openocd + gdb，还差仿真器没建起来

**Comment by Artistrs** [comment]
我刚看老师的视频了，选那个高速的DAPLink更好是吧！如果用着合适，我会推荐到下面的论坛里：
https://forum.rvspace.org/t/connecting-to-visionfive-s-jtag-port-a-short-guide/514

**Comment by wuxx** [comment]
好的，高速的速度更快一些，日常使用用普通速度的一般也够了

**Comment by Artistrs** [comment]
还有请问老师，我不打算焊接JTAG插接头，怎么接线更好，下面是图片页面，https://forum.rvspace.org/t/connecting-to-visionfive-s-jtag-port-a-short-guide/514，

**Comment by wuxx** [comment]
一般用杜邦线连接即可

**Comment by Artistrs** [comment]
老师，若不焊接，那七个通孔怎么接杜邦线？

**Comment by wuxx** [comment]
https://github.com/wuxx/nanoDAP/wiki/%E5%85%B3%E4%BA%8E%E6%8E%A5%E7%BA%BF%E8%AF%B4%E6%98%8E

**Comment by Artistrs** [comment]
https://item.taobao.com/item.htm?spm=a1z10.5-c.w4002-21349689069.20.2b254af5TLGSqz&id=605653531236
老师，这款也可作为USB转TTL使用是吧

**Comment by wuxx** [comment]
可以

**Comment by Artistrs** [comment]
老师，我看上面的链接也没看明白https://github.com/wuxx/nanoDAP/wiki/%E5%85%B3%E4%BA%8E%E6%8E%A5%E7%BA%BF%E8%AF%B4%E6%98%8E，VisionFive开发板上那标着A的7个通孔(https://forum.rvspace.org/t/connecting-to-visionfive-s-jtag-port-a-short-guide/514%EF%BC%8C)，必须焊接上插针吗？有没有免焊接的插针座？

**Comment by wuxx** [comment]
需要焊插针

**Comment by wuxx** [comment]
如果不焊插针，可以看看这种夹子行不行
![image](https://user-images.githubusercontent.com/1648489/176988633-62f8fd2f-f99d-4d64-b254-e1db055e17fc.png)

**Comment by Artistrs** [comment]
感谢老师解惑！！！
