### ISSUE TITLE
烧录 STM32F401 失败

### ISSUE THREAD

**Issue by myst729** [wuxx/nanoDAP#25]
不慎刷入一个带写保护的 tinyuf2 固件，按照对方建议要烧录其他固件只能用下载器。手头只有一个 CMSIS-DAP / nanoDap 2.2，烧录失败，看这条评论说是下载器的问题 https://github.com/adafruit/tinyuf2/pull/189#issuecomment-1163257209

请问是需要升级下载器固件吗？

**Comment by wuxx** [comment]
下载器固件一般不需要再去升级

**Comment by myst729** [comment]
那请问会是什么原因呢？业余选手有点找不到方向 😢 pyocd 的问题？

**Comment by wuxx** [comment]
一般需要先用stlink去除写保护

**Comment by myst729** [comment]
买了个十块钱的盗版stlink救回来了
