### ISSUE TITLE
不识别芯片怎么回事啊 

### ISSUE THREAD

**Issue by bihailantian655** [wuxx/nanoDAP#27]
我用的103cb开发板，刷的固件，想测试一下能不能用。
![MWN@7ZH @2 _FYUE8C@%9K9](https://user-images.githubusercontent.com/35267721/234832167-b0d45eef-a324-426d-a256-365aa0beae47.png)
这俩100r 的电阻没接   （swclk dio）直接接的目标板。

R9   R1 也没接。

![98QF69CFSXC(3CWKNWWRKN6](https://user-images.githubusercontent.com/35267721/234832455-c7a688d8-b170-4dd5-af5c-bd7c712a8dcf.png)

keil中能识别 daplink ，刷的是2.3的这俩固件测试都不行。
![83`D5%BS$TA2C06DYBR3CUF](https://user-images.githubusercontent.com/35267721/234832702-4a83c43a-355d-4cd7-871f-e0c555979a5b.png)

under reset 和 norml 都不行
![LQFTF1}IOHFNYEE3$T $42R](https://user-images.githubusercontent.com/35267721/234833176-7e5811c3-e116-4187-862a-399729a3babf.png)

**Comment by bihailantian655** [comment]
开发板原来的pb12 pb13引脚有外围电路，更改引脚为pb10 pb11以后。
出现了一个现象就是
keil 连接4个jtag 引脚 能用swd 模式识别芯片， jtag模式不能识别芯片
 只连接swdio swclk  gnd vcc    swd模式 不能识别被烧录的芯片。

**Comment by LiHangBing** [comment]
[RadioOperator](https://github.com/RadioOperator)
/
[STM32F103C8T6_CMSIS-DAP_SWO](https://github.com/RadioOperator/STM32F103C8T6_CMSIS-DAP_SWO)
这个里面的蓝色药丸remap固件实测可以识别
