### ISSUE TITLE
NXP MCUXpresso IDE 无法连接

### ISSUE THREAD

**Issue by MrAMS** [wuxx/nanoDAP#28]
使用NXP MCUXpresso IDE 的 LinkServer连接RT1064板子时，IDE报错：

![D4PP7%3(32RVXPZYC3TE9@9](https://github.com/wuxx/nanoDAP/assets/25056812/3598d37b-158e-41ef-beac-700fcbed0bfc)

详细信息：

> Error in final launch sequence:
> 
> Failed to execute MI command:
> -target-select extended-remote localhost:10989
> Error message from debugger back end:
> Remote communication error.  Target disconnected.: (undocumented errno 10061).
> Failed to execute MI command:
> -target-select extended-remote localhost:10989
> Error message from debugger back end:
> Remote communication error.  Target disconnected.: (undocumented errno 10061).
>

**Comment by MrAMS** [comment]
已排查接线问题，
NXP LinkServer配置如下：
![image](https://github.com/wuxx/nanoDAP/assets/25056812/43f230a9-eabf-4d3b-bf72-b80fd2ee31d5)
![image](https://github.com/wuxx/nanoDAP/assets/25056812/97db9b5b-b106-46fe-820a-c8cfef32b0e8)

**Comment by wuxx** [comment]
先试试看用有线的可以吗

**Comment by MrAMS** [comment]
已经识别上了而且LinkServer连接上了
![image](https://github.com/wuxx/nanoDAP/assets/25056812/ea998b54-26dd-4a0b-bf2f-d388a2fd7f1a)
身边暂时没有其他的DAP
