### ISSUE TITLE
Ubuntu烧写时 /stm32f4x.cfg:45: Error: target requires -dap parameter instead of -chain-position!

### ISSUE THREAD

**Issue by HowieHepburn** [wuxx/nanoDAP#29]
终端：openocd -f /usr/share/openocd/scripts/interface/cmsis-dap.cfg -f /usr/share/openocd/scripts/target/stm32f4x.cfg -c init -c halt -c "flash write_image erase /home/howie/32_prj/p-centerborad/build/P-centerborad.bin 0x08000000" -c reset -c shutdown
Open On-Chip Debugger 0.12.0+dev-00271-g2c57d11c7-dirty (2023-07-19-20:04)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : auto-selecting first available session transport "swd". To override use 'transport select <transport>'.
**_**/usr/share/openocd/scripts/target/stm32f4x.cfg:45: Error: target requires -dap parameter instead of -chain-position!
in procedure 'script'**_** 
at file "embedded:startup.tcl", line 28
at file "/usr/share/openocd/scripts/target/stm32f4x.cfg", line 45
make: *** [Makefile:201：download] 错误 1

对应的
$_TARGETNAME configure -work-area-phys 0x20000000 -work-area-size $_WORKAREASIZE -work-area-backup 0

**Comment by wuxx** [comment]
看上去是脚本的配置有问题
