### ISSUE TITLE
MDK编译后丢失很多文件

### ISSUE THREAD

**Issue by ZyonMo** [wuxx/nanoDAP#3]
您好，MDK编译后丢失很多文件，按照您的提示安装了MDK5.15，CMSIS.5.4.0，造成这个原因主要是您建立这个文件的时候有太多文件的依赖关系在您的电脑其他文件里，导致您把这个项目打包上来时丢了依赖的文件，然后我很难找您的文件，您看下能否把依赖的文件也包含进来，这样移植性就很高了，谢谢。

**Comment by wuxx** [comment]
应该是这位朋友安装MDK时候部分库没安装全，
C:\Keil_v5\ARM\RV31和C:\Keil_v5\ARM\RL 这两个目录是编译时候需要的访问的，重新从其他拷贝这两个目录加入编译就可以了

**Comment by wuxx** [comment]
已经压缩放到doc目录下了，下载下来直接解压到keil_v5/ARM/目录下应该就可以了
https://github.com/wuxx/nanoDAP/tree/master/doc
