### ISSUE TITLE
串口悬空的时候会不停的发二进制0

### ISSUE THREAD

**Issue by MomentDerek** [wuxx/nanoDAP#4]
![image](https://user-images.githubusercontent.com/40252940/62508180-4ca46680-b839-11e9-8054-9abf7a39635d.png)

串口悬空就会这样，但是接上开发板后恢复正常

**Comment by MomentDerek** [comment]
查找到了问题所在，就是串口的rx脚没有默认上拉，硬件上拉后恢复正常，但是代码我跑不通，firmware里面提供的固件可以使用，但是software里面的c8t6程序在修复完所有的文件关联后能够编译通过，但是下载后无法使用

**Comment by wuxx** [comment]
参考的哪个硬件和软件版本？

**Comment by MomentDerek** [comment]
> 参考的哪个硬件和软件版本？

哦哦哦，忘了，是c8t6版的

**Comment by MomentDerek** [comment]
> 参考的哪个硬件和软件版本？

cbt6版本的cmsis-dap固件没有问题，但是要么只有拖拽，有么其他功能齐全没拖拽

**Comment by wuxx** [comment]
有 v1.0 v2.0 v2.1几个版本，硬件和软件需要一一对应

**Comment by wuxx** [comment]
串口的问题应该不影响正常使用

**Comment by MomentDerek** [comment]
确实不影响使用……但是发现了bug不修一下吗23333

**Comment by wuxx** [comment]
有的人认为是bug，有的人认为不是。就我所知，市面上所有其他串口工具都是没有上拉的
