### ISSUE TITLE
建议在readme 加上feature list

### ISSUE THREAD

**Issue by busydoggo** [wuxx/nanoDAP#7]
建议在readme 加上feature list
![feature](https://user-images.githubusercontent.com/32995778/68071502-bdd0b880-fd59-11e9-870e-45d2104fd564.png)

**Comment by phone13543016677** [comment]
老大, 我也借鉴你的方案了. 
之前CMSIS-DAP做了三线自动复位的, DAPLink也打算改改, 但自行改了几次工作都不太稳定, 不知道哪里出问题了, 直至后来发现你的开源方案.
完善后, 打算也挂到淘宝上, 赚点烟钱, 弄个钱不容易吖~~~ 
硬件上,  参考了官方图,技小新,电子创客营的, 还有老大你的, 综合修改, USB上拉修改了一点, 删了4个作用不大的电阻,烧录口加退耦......
软件上,  以你的开源代码为主, 配合几个网上方案作修改的,  
目前在自家win7上, 三线软复, 10M, 棒棒的.
老大, 有空多联系指导:  safang@139.com

**Comment by wuxx** [comment]
可以的，方案本来就是开源的，大家都可以做，一起推广DAPLink :)
