### ISSUE TITLE
无法给探索者F4下载程序

### ISSUE THREAD

**Issue by luhua2018** [wuxx/nanoDAP#8]
有一个问题，这个下载器无法给原子探索者F4的开发板下载程序，芯片倒是可以间歇性的识别出来一下，但是下载程序肯定出错。

我给同一个下载器烧了jlink-OB固件就可以正常用，但是用DAP就不行，不知道这个问题是什么原因。

**Comment by wuxx** [comment]
你好，请问是你自己制作的dap，还是我们这里购买的？
如果jlink-ob可用，说明硬件应该是没问题的，可以检查以下几点
1.  杜邦线是否接触良好，尝试换一组杜邦线试试看
2. 尝试将速度调低
3. 确认目标板供电是否没问题

**Comment by luhua2018** [comment]
常规办法都已经试过了，剩下的都是玄学问题：

1. 杜邦线缩到了 5cm ，速度降到了 50k ，供电也保证没问题。

2. 同样的条件下刷 JLink 固件就可以用 DAP 固件就不行。

3. 我查了探索者开发板的原理图发现它的 TCK 是 10k 下拉的，当我把它改成 10k 上拉后芯片可以被识别到了但是下载仍然出错。

所以我怀疑可能是 DAP 的驱动能力不足？毕竟探索者开发板的 jtag 接口离芯片有点远，可是同样的下载器刷 JLink 固件又能正常用。不知道这种情况有没有可能通过软件解决？

下载器是从淘宝店买的。我这里只有这一种 DAP ，好像正点原子官方也出了 DAP 下载器不知道他们有没有遇到这种情况。

![下载报错](https://i.loli.net/2020/04/04/PXvLGKrWDln3pFN.png)

![淘宝订单截图](https://i.loli.net/2020/04/04/6WuDptIO9bZRBGX.png)

**Comment by wuxx** [comment]
1. 能否换另一块板子试试看？确定是dap的问题还是和板子有关系
2. 不知道你是怎么供电的，如果目标单板单独供电，建议dap只连接3根线 gnd clk io调试，不要接上3.3V
3. 调整杜邦线线序，让gnd夹在clk和io的中间，改善信号质量

**Comment by luhua2018** [comment]
其他板子 F1 的、F0 的都没问题，只有特定的`正点原子的探索者F407开发板`不行。

算了，不纠结这个问题了，也许是他板子本身设计的 BUG 。
